### ISSUE TITLE
Problem with selected date on Calendar

### ISSUE THREAD

**Issue by arashackdev** [pasoonate/calendar-view#1]
Hi,

![calendar-code](https://user-images.githubusercontent.com/19420485/50051923-cb288880-0130-11e9-8248-9a8cbcf4e9d7.PNG)

the date selected is 27 but the selection class remains on **today** all the time.

**Comment by ataiemajid63** [comment]
> Hi,
> 
> ![calendar-code](https://user-images.githubusercontent.com/19420485/50051923-cb288880-0130-11e9-8248-9a8cbcf4e9d7.PNG)
> 
> the date selected is 27 but the selection class remains on **today** all the time.

The calendar-view don't set class "calendar-day-view-selected" for day by default. Please check component that uses the calendar-view component.
