### ISSUE TITLE
Pasoonate file is not included in project

### ISSUE THREAD

**Issue by alishefaee** [pasoonate/calendar-view#11]
با سلام
فایل اصلی 
<script src="../node_modules/pasoonate/dist/pasoonate.js"></script>
در گیت هاب نیست .
آیا این پروژه قابل استفاده در ری‌اکت یا نودجی اس هست؟

**Comment by ataiemajid63** [comment]
سلام
فایل pasoonate.js در پوشه dist وجود دارد.
برای استفاده در پروژه‌های nodejs و reactjs از پروژه اصلی استفاده کنید.
